- README.md
- src/index.js
I used the default index directly from the `swagger-ui` package, so it can be automatically updated instead of having to have to manually fix in case of `swagger-ui` package updates.
> Added option to display default Swagger UI (closes #38)

- README.md
- src/index.js
Adds config `prefix` and `versionPrefix` options to support API with prefixing/versioning.
> Added config option to support api prefixing and versioning (fix #39)

- src/index.js
If no versionPrefix is passed in the config, then things like tags in the docs will have extra whitespace. Like:
```js
{
// ... stuff
"tags": [
{
"name": "auth ", // <--- extra whitespace
"description": "A auth service",
"externalDocs": {}
},
{
"name": "users ",  // <--- extra whitespace
"description": "A users service",
"externalDocs": {}
}
],
// ... more stuff
}
```
> Fix extra whitespace if no versionPrefix is passed in config.

- src/index.js
If the feathers app that this plugin is configured on is mounted at a prefixed URL, the redirect breaks.
> Fix 'text/html' redirect not respecting mountpath

- src/utils.js
Simple change that allows for an alternative syntax in services that in some cases would read better (IMO). Example (with a theoretical decorator that we could even ship):
```js
@docs({
description: 'My cool service.'
})
class MyService {
@docs({
description: 'Create the cool thing.',
parameters: [],
responses: {}
})
create () {
// Do the thing
}
@docs({
description: 'Find cool things.',
parameters: [],
responses: {}
})
find () {
// Do the thing
}
}
```
Or just use getters in a clever fashion.
```js
class MyService {
get docs () {
return {
description: 'My cool service.'
}
}
get create () {
return Object.assign(this._create, {
docs: {
description: 'Create the cool thing.',
parameters: [],
responses: {}
}
})
}
_create () {
// Do the thing
}
get find () {
return Object.assign(this._find, { …
```
> Allow each method of a service to define docs.

- src/index.js
This is a little more verbose, but it eliminates the creation of empty paths for services that don't implement all the operations.
> Don't add empty paths

- src/index.js
I apologize. I was cleaning up my repo and deleted the branch, which closed the PR. here is the same PR as #64
Been trying to dig into Feathers recently, and like it very much so far! Found feathers-swagger, which made things even better. XD Found a bit of missing functionality, though.
As far as I can tell, this should fully backwards compatible.
1. The id names are fixed to `resourceId` (at least in the parameters, though the url is set properly). The type is also fixed at `integer`. The parameter name is now set the same way the URL was before, and the type still defaults to `integer`, but can be overwritten at `docs.idType`.
2. Only the getWithId endpoint had any responses defined, and only the 200, and with no schema. All endpoints have the appropriate responses (as far as I can …
> Quality of life

- package-lock.json
- package.json
- src/index.js
- test/index.test.js
Adding test for Buzzard provider API.
Refactoring mixin/plugin to be a separate function, allowing input parameters to swap depending on Feathers version.
Original issue: https://github.com/feathersjs-ecosystem/feathers-swagger/issues/83
> Fix: Adding support for Buzzard provider syntax (#83)

- README.md
There is an error in the documentation. The items in an array are defined via a `items`-property  instead of `schema`.
>  fix(documentation): Array items reference

- README.md
Minor improvements in syntax highlighting of the `README.md`.
* `js` and `shell` syntax highlighting for codeblocks
* Short syntax for URL's.
* Copyright updated
> fix(documentation): Improved markdown highlighting

- lib/index.js
- lib/utils.js
- test/index.test.js
It is possible to define `idType` (by default `"integer"`) per service. This PR adds an optional param `idType` to the root configuration object. The value is the default but can be overwritten.
* The changes are backwards compatible.
* I added the param to the test. I'm not really proud of the way it is, but there is a test. A test setup with multiple instances would be an option in the future, but adds complexity (failed shutdowns, timing, ports).
> Config contains idType to set default for application

- README.md
This is one possible solution to fix the broken badges mentioned in #103. There could also be another solution by changing account details on the codeclimate page and get the other namespace to work.
> fix(documentation): Codeclimate badges

- lib/index.js
Why this PR?
On my work we use feathers-swagger for various services. We wanted to add a few more queries for the find method and also customize the descriptions according to our wishes.
We searched for a long time and did not find any specific way to solve this problem. Therefore, we decided ourselves to add a parameter that allows us to do what we want.
What have I done?
I've added a new Parameter `findQueryParameter`. It is now possible to add new QueryParamters or change the description of the default QueryParamters by adding this Paramter to your swaggerConfig.
In my CodeExample it will look like this:
app.configure(
swagger({
findQueryParameters: [
{
description: "This is another Description about the query parameter",
in: "query",
name: "$limit",
type: "integer"
},
....
],
tags: [ …
> added findQueryParameters

- example/app.js
- lib/index.js
- lib/utils.js
Standardise some basic formatting:
- string concatenation uses backticks
- strings with double quotes have been replaced with single quotes
- object keys only have quotes where required
- default response codes are ordered numerically
> chore: Standardise concatenation and object keys

- lib/index.js
- lib/utils.js
In the swagger spec, secutiry should be an array of securityDefinition
names and not an object.
This is a small part of #117 by @wnxhaja
> fix: Default security value should not be an object

- lib/utils.js
The secirutyDefinitions key should only be persent at the top level, not
for each operation.
https://swagger.io/docs/specification/2-0/authentication/basic-authentication/
> fix: Remove invalid securityDefinitions key from operations

- lib/index.js
feathers-swagger adds a number of invalid keys to the root level
document that throw warnings when passing the generated file into e.g
https://editor.swagger.io/.
This is a small part of #117 by @wnxhaja
> fix: Remove invalid root level keys from swagger file

- README.md
- example/app.js
- lib/index.js
- lib/utils.js
- package-lock.json
- package.json
- test/index.test.js
Before starting to add openapi 3 support I though it would be good to release another 0.7 version, that outputs valid swagger v2.
* add test to validate the generated swagger specification (using [swagger-parser](https://www.npmjs.com/package/swagger-parser))
* include https://github.com/feathersjs-ecosystem/feathers-swagger/pull/89 to add version
* fix incorrect default basePath
* fix default empty externalDocs of tags
As I already stated, I would also help to maintain this repo.
> Add test to validate swagger specification, fix spec errors

- types/index.d.ts
This PR adds typings for `docs` in the following example:
```ts
const messageService = memory();
// `docs` will be typed correctly.
messageService.docs = {
// ...
};
```
> Added typings for custom Swagger specfications generation.

- README.md
- lib/openapi.js
- lib/utils.js
- lib/v2/generator.js
- lib/v3/generator.js
- test/utils.test.js
- test/v3/generator.test.js
- types/index.d.ts
- types/test.ts
Added support for array `service.id` to support the composite PK feature in [feathers-objection](https://github.com/feathersjs-ecosystem/feathers-objection) & [feathers-cassandra](https://github.com/feathersjs-ecosystem/feathers-cassandra).
`service.docs.idType` option can now be also set to an array of types for the parameters in `service.id`.
`service.options.idSeparator` (default: `,`) is being used to separate the ID fields in the path, e.g. `/users/{firstId},{secondId}`.
See issue https://github.com/feathersjs-ecosystem/feathers-swagger/issues/194 for more details.
> Added support for array `service.id`

- README.md
I have faced the issue of missing `https` scheme myself. This could help others find the info faster.
> Add scheme note

- README.md
- lib/openapi.js
- test/v3/generator.test.js
- types/index.d.ts
- types/index.test-d.ts
* allow disabling of methods via the option `defaults.operations` by setting it to false for a method.
* allow disabling of methods by returning null from an operation generator set at `defaults.operationGenerators`
closes #214
> feat: allow disabling of methods from defaults

- lib/v3/generator.js
I was using https://github.com/acacode/swagger-typescript-api to generate a TypeScript client based on the swagger file created by `feathers-swagger` and one issue I ran across is that pagination results had all optional properties.
Like this
```ts
/** Company pagination result */
export interface CompanyPaginationType {
total?: number;
limit?: number;
skip?: number;
data?: CompanyListType;
}
```
I believe this is not correct, so this PR address that and the outputted type looks like this now
```ts
/** Company pagination result */
export interface CompanyPaginationType {
total: number;
limit: number;
skip: number;
data: CompanyListType;
}
```
> Include required in pagination result

- package.json
A couple of optional peer dependencies were not declared in the package.json. This prevents compatibility with modern versions of yarn, since yarn will block access to undecalred dependencies.
This adds the missing peer dependencies and marks them as optional so they only need to be installed when actually required
I've only tested with koa. It is possible that other setups might require similar peer dependencies that I did not have problems with. However a quick look at the documentation did not mention other peer dependencies in the installation section
> fix(deps): add missing optional peer dependencies
